### ISSUE TITLE
Update documentation for database setup

### ISSUE THREAD

**Issue by duaimei** [duaimei/civic_hacking_hub#28]
There have been some changes to how the database is setup recently. In the installation instructions add a section for database setup:

`brew install postgres`
from the root directory:
`cp secrets.example.js secrets.js`
Open up that file and replace the database username and password with something valid on your machine
use those credentials to log into postgres and create the following database:
CREATE DATABASE civic_hacking;
Then you can use the instructions in the README found in `server/db/README.md`

Include some resources to help navigate postgres:

https://wiki.postgresql.org/wiki/Homebrew 
https://gist.github.com/Kartones/dd3ff5ec5ea238d4c546

**Comment by mcruzdev** [comment]
I think that we can wait for this #29 issue to be complete.

What do you think? If we want to create two ways to create a database I can do it ( assign it for me) 🚀
