### ISSUE TITLE
upgrade node version

### ISSUE THREAD

**Issue by duaimei** [duaimei/civic_hacking_hub#32]
I don't know what version I was using on my other laptop but
nvm use lts/dubnium 

works when you npm i --force

it should just be using --lts

**Comment by ridays2001** [comment]
@duaimei Hello,
Can you tell me what exactly do you want to do?

**Comment by duaimei** [comment]
Hi @ridays2001 , Thank you very much for inquiring about this. I went ahead and upgraded nuxt and defined the node version in the package.json. 

I'm going to close this issue, but If you want to work on something else I will definitely work with you!
