### ISSUE TITLE
Landing Page Update

### ISSUE THREAD

**Issue by duaimei** [duaimei/civic_hacking_hub#42]
Move the current [index.vue](https://github.com/duaimei/civic_hacking_hub/blob/dev/pages/index.vue) file to the [project folder](https://github.com/duaimei/civic_hacking_hub/tree/dev/pages/project)

create a new index.vue in the page directory. Use the [template.vue](https://github.com/duaimei/civic_hacking_hub/blob/dev/template.vue) file. 

Add an h1 attribute inside the div tags that says "Welcome to the Civic Hacking Hub"

**Comment by varnaa** [comment]
@duaimei hi, I'd like to work on this issue.
