### ISSUE TITLE
Update Navbar nuxt link

### ISSUE THREAD

**Issue by duaimei** [duaimei/civic_hacking_hub#45]
In the components/NavBar.vue

Find the Nuxt link that goes to Project and update it from 

`<div class="col-2"><nuxt-link to="/">Projects</nuxt-link></div>`

to

`<div class="col-2"><nuxt-link to="/project">Projects</nuxt-link></div>`

**Comment by valwebd** [comment]
Assign me, please.

**Comment by duaimei** [comment]
Thank you so much!
