### ISSUE TITLE
Edit Project Migration file to include language_tags

### ISSUE THREAD

**Issue by duaimei** [duaimei/civic_hacking_hub#51]
Inside of the: server/db/migrations/20200113212529_create_projects.js

add

table.json('language_tags')

on its own line between:
table.string('setup_link', 250)
 table.integer('code_organization_id').unsigned()

https://knexjs.org/#Schema-json
This can be verified by setting up the postgres database and following the directions in the database README: server/db/README.md

**Comment by rheimon1** [comment]
Hello @duaimei ! Can you assign it to me?

**Comment by duaimei** [comment]
Hack yes! Please let me know if you run into any issues!

**Comment by rheimon1** [comment]
@duaimei,  can i add it to server/db/migrations/20200113212529_create_projects.js or would I need to create another migration?

**Comment by duaimei** [comment]
You can just add it to the same file.

**Comment by duaimei** [comment]
Normally, it is better practice to add a new migration that creates a new field, but I need to get this project working in Heroku again anyways, so I'm just going to blow the database away.
