### ISSUE TITLE
NavBar css fix

### ISSUE THREAD

**Issue by duaimei** [duaimei/civic_hacking_hub#53]
The css library has been changed from BootStrap to Tailwind. Tailwind is great because you just put the keywords in the `class=""` and the framework knows how to handle it. 

Here is an example Nuxt navbar:
https://www.limosyn.com/posts/creating-navbar-and-footer-in-nuxtjs-with-tailwindcss

in `components/NavBar.vue`
change the enclosing `<div class="row"></div>`
to `<nav></nav>`

and use the classes in the example for the nuxt links until  all of the elements are on one line and spaced nicely starting from the top left.

make the nav background color `bg-primary`

A great reference for tailwind: https://nerdcave.com/tailwind-cheat-sheet

**Comment by Areadrill** [comment]
Hi. I'd love to help with this. It seems to me like there's something wrong with the text in the issue though. 

> Change the enclosing

and then a bunch of blank lines. 

Should there be something there?

**Comment by duaimei** [comment]
Thank you for pointing that out! It didn't like the fact that I included code without marking it as code.

I have assigned this task to you. Let me know if you have any questions!

**Comment by Areadrill** [comment]
I'll take care of this tomorrow!
