### ISSUE TITLE
knexfile.js possible error

### ISSUE THREAD

**Issue by mcruzdev** [duaimei/civic_hacking_hub#56]
Hi @duaimei, how are you?

I am new with VueJS, but I want to learn :)

I saw that the knexfile.js is importing a file called `./sercets` and probably it can make a mistake in future, should be `./secrets` because we have a file `secrets.example.js`

**Comment by duaimei** [comment]
Please pull down! I just fixed it!

There's some pending documentation changes:

cp secrets.example.js secrets.js

then make a civic_hacking database in your postgres database using those credentials

then 

knex migrate:latest

should get you to a working state!

**Comment by duaimei** [comment]
I'm sorry for merging that in without making sure that it works!

The documentation issue is: https://github.com/duaimei/civic_hacking_hub/issues/28

Please let me know if my above comment helped you!

**Comment by mcruzdev** [comment]
No problem, I got it :)

Yes, your comment help me!
