### ISSUE TITLE
Add information to development seeds: Coding Orgs

### ISSUE THREAD

**Issue by duaimei** [duaimei/civic_hacking_hub#59]
This is needed in order to have the site show information correctly:

server/db/seeds/development/code_organizations.js

The available fields are listed here:
server/db/migrations/20200113212517_create_code_organizations.js

I have the name in the seeds, but I need the url and the description

The three that I have listed are:
Ruby For Good: https://rubyforgood.org/
Code For America: https://www.codeforamerica.org/
Code For DC: https://codefordc.org/

But if you're aware of any other coding organizations that support non-profits, I'd appreciate you adding them!

**Comment by DanTcheche** [comment]
Hi, I can take this issue if you want to assign it to me. Thank you!

**Comment by DanTcheche** [comment]
I just opened the pull request. Thank you!
