### ISSUE TITLE
Implement Cypress

### ISSUE THREAD

**Issue by duaimei** [duaimei/civic_hacking_hub#6]
The problem:
In order to test behavior, I would like to use Cypress.

How to implement?
https://docs.cypress.io/guides/getting-started/installing-cypress#Installing
npm install cypress --save-dev

npx cypress open
^ should initialize the cypress folder. Delete the default tests, and just create a simple hello world test that verifies that the landing page loads. More tests issues will be created after the initial setup.

If you have questions, feel free to ask!

**Comment by mcruzdev** [comment]
I can do it @duaimei 🚀
