### ISSUE TITLE
Change NuxtJS telemetry options

### ISSUE THREAD

**Issue by mcruzdev** [duaimei/civic_hacking_hub#62]
We are using `npm run dev` script to develop the application without running `npm start` every each change.

But all time, we receive this message requiring our decision:

<img width="575" alt="Captura de Tela 2021-10-04 às 02 51 09" src="https://user-images.githubusercontent.com/56329339/135800812-07b10e0d-2016-45cd-9a9c-b6b71b363471.png">

To change it we can add the telemetry option to false: https://github.com/nuxt/telemetry

@duaimei, what do you think about it?

**Comment by duaimei** [comment]
<img width="834" alt="Screen Shot 2021-10-04 at 12 53 26 PM" src="https://user-images.githubusercontent.com/7873934/135892135-b1f642a8-56b5-4ff1-9c1b-690afe844ad4.png">

Actually, I assigned this to you because you brought it up, but let me know if you would prefer if someone else do it.

**Comment by mcruzdev** [comment]
Hahahah nice image :)

I can do it, no problem :)
