### ISSUE TITLE
Improve dev environment

### ISSUE THREAD

**Issue by Areadrill** [duaimei/civic_hacking_hub#68]
I believe this project would benefit from a dockerized environment for development (and eventually even deployment).

It would be possible to creata a docker-compose environment containing postgres and node, which would make setup a lot easier.

**Comment by duaimei** [comment]
Thank you! I appreciate the feedback! There's already an issue for Dockerization - https://github.com/duaimei/civic_hacking_hub/issues/29, and someone is working on it!

**Comment by Areadrill** [comment]
Awesome, I'll close this one then.
