### ISSUE TITLE
Create new migration for a through table

### ISSUE THREAD

**Issue by amycommits** [duaimei/civic_hacking_hub#72]
There is a README file for how to make a knex migration: https://github.com/duaimei/civic_hacking_hub/blob/dev/server/db/README.md

I did not realize that the formatting was so messed up because I normally look at it locally -.-', so if you want to fix it that would be great! But here's the main task.

$ knex migrate:make code_project_nonprofit

This should create a new file in server/db/migrations

Then use the same type of logic found in https://github.com/duaimei/civic_hacking_hub/blob/dev/server/db/migrations/20200113212529_create_projects.js#L16

to make the following three columns:
code_organization_id
project_id
nonprofit_organization_id

plus timestamps
https://github.com/duaimei/civic_hacking_hub/blob/dev/server/db/migrations/20200113212529_create_projects.js#L13

**Comment by bstuff** [comment]
can I take?
